# Generated by Django 5.0.4 on 2024-05-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fuel',
            new_name='motor',
        ),
    ]
